name: CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      uses: dante-ev/latex-action@master
      with:
        root_file: cv.tex
    - name: Deploy   
      uses: actions/upload-artifact@v1
      with:
        name: cv.pdf
        path: cv.pdf
